Fix workflow build

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -1,28 +1,38 @@
 name: Codestyle and build check
 
-on:
-  push:
-    branches: '*'
-  pull_request:
-    branches: '*'
+on: [push]
 
 jobs:
   build:
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: ./src
     strategy:
       matrix:
         node-version: [18.x]
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v2
+
         with:
           node-version: ${{ matrix.node-version }}
-          cache: 'npm'
+
       - name: Install dependencies
         run: npm install
+
       - name: Check codestyle
         run: npx prettier --check .
-      - name: Run build
-        run: npm run build
+
+      - name: Start Application
+        run: node index.js &
+      - name: Wait for Application to Start
+        run: |
+          for i in $(seq 1 10); do
+            curl -sSf http://localhost:3000 > /dev/null && echo "Application is running!" && exit 0
+            sleep 1
+          done
+          echo "Application failed to start" && exit 1
